#drivers/input/touchscreen/focaltech_ts/focaltech_test
#
# Makefile for test module
#
# Linux driver folder
# [Arima_4101][allen_yu] LightPhone ft3417 touch driver porting and dynamic detect ft3267 and ft3417 20181227 begin
obj-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_test_ft3267.o
# [Arima_4101][allen_yu] 20181227 end