#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

# [Arima_4101][allen_yu] LightPhone ft3417 touch driver porting and dynamic detect ft3267 and ft3417 20181227 begin
obj-$(CONFIG_TOUCHSCREEN_FT3267)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FT3267)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FT3267)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FT3267)	+=  focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FT3267)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FT3267)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FT3267)   +=  focaltech_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FT3267)   +=  focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FT3267)   +=  focaltech_flash/
obj-$(CONFIG_TOUCHSCREEN_FT3267)   +=  focaltech_test/
# [Arima_4101][allen_yu] 20181227 end
