#drivers/input/touchscreen/focaltech_touch/focaltech_test
#
#Makefile for test module
#


# [Arima_4101][allen_yu] LightPhone ft3417 touch driver porting and dynamic detect ft3267 and ft3417 20181227 begin
obj-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_test.o
obj-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_test_ini.o
obj-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_test_detail_threshold.o
obj-$(CONFIG_TOUCHSCREEN_FT3267) += supported_ic/
# [Arima_4101][allen_yu] 20181227 end
